<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array(
            ["id" => "1101", "m_province_id" => "11", "level" => "kabupaten", "name" => "simeulue", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1102", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh singkil", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1103", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1104", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh tenggara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1105", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1106", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1107", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1108", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh besar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1109", "m_province_id" => "11", "level" => "kabupaten", "name" => "pidie", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1110", "m_province_id" => "11", "level" => "kabupaten", "name" => "bireuen", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1111", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1112", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh barat daya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1113", "m_province_id" => "11", "level" => "kabupaten", "name" => "gayo lues", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1114", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh tamiang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1115", "m_province_id" => "11", "level" => "kabupaten", "name" => "nagan raya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1116", "m_province_id" => "11", "level" => "kabupaten", "name" => "aceh jaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1117", "m_province_id" => "11", "level" => "kabupaten", "name" => "bener meriah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1118", "m_province_id" => "11", "level" => "kabupaten", "name" => "pidie jaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1171", "m_province_id" => "11", "level" => "kota", "name" => "banda aceh", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1172", "m_province_id" => "11", "level" => "kota", "name" => "sabang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1173", "m_province_id" => "11", "level" => "kota", "name" => "langsa", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1174", "m_province_id" => "11", "level" => "kota", "name" => "lhokseumawe", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1175", "m_province_id" => "11", "level" => "kota", "name" => "subulussalam", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1201", "m_province_id" => "12", "level" => "kabupaten", "name" => "nias", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1202", "m_province_id" => "12", "level" => "kabupaten", "name" => "mandailing natal", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1203", "m_province_id" => "12", "level" => "kabupaten", "name" => "tapanuli selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1204", "m_province_id" => "12", "level" => "kabupaten", "name" => "tapanuli tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1205", "m_province_id" => "12", "level" => "kabupaten", "name" => "tapanuli utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1206", "m_province_id" => "12", "level" => "kabupaten", "name" => "toba samosir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1207", "m_province_id" => "12", "level" => "kabupaten", "name" => "labuhan batu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1208", "m_province_id" => "12", "level" => "kabupaten", "name" => "asahan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1209", "m_province_id" => "12", "level" => "kabupaten", "name" => "simalungun", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1210", "m_province_id" => "12", "level" => "kabupaten", "name" => "dairi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1211", "m_province_id" => "12", "level" => "kabupaten", "name" => "karo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1212", "m_province_id" => "12", "level" => "kabupaten", "name" => "deli serdang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1213", "m_province_id" => "12", "level" => "kabupaten", "name" => "langkat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1214", "m_province_id" => "12", "level" => "kabupaten", "name" => "nias selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1215", "m_province_id" => "12", "level" => "kabupaten", "name" => "humbang hasundutan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1216", "m_province_id" => "12", "level" => "kabupaten", "name" => "pakpak bharat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1217", "m_province_id" => "12", "level" => "kabupaten", "name" => "samosir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1218", "m_province_id" => "12", "level" => "kabupaten", "name" => "serdang bedagai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1219", "m_province_id" => "12", "level" => "kabupaten", "name" => "batu bara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1220", "m_province_id" => "12", "level" => "kabupaten", "name" => "padang lawas utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1221", "m_province_id" => "12", "level" => "kabupaten", "name" => "padang lawas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1222", "m_province_id" => "12", "level" => "kabupaten", "name" => "labuhan batu selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1223", "m_province_id" => "12", "level" => "kabupaten", "name" => "labuhan batu utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1224", "m_province_id" => "12", "level" => "kabupaten", "name" => "nias utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1225", "m_province_id" => "12", "level" => "kabupaten", "name" => "nias barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1271", "m_province_id" => "12", "level" => "kota", "name" => "sibolga", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1272", "m_province_id" => "12", "level" => "kota", "name" => "tanjung balai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1273", "m_province_id" => "12", "level" => "kota", "name" => "pematang siantar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1274", "m_province_id" => "12", "level" => "kota", "name" => "tebing tinggi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1275", "m_province_id" => "12", "level" => "kota", "name" => "medan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1276", "m_province_id" => "12", "level" => "kota", "name" => "binjai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1277", "m_province_id" => "12", "level" => "kota", "name" => "padangsidimpuan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1278", "m_province_id" => "12", "level" => "kota", "name" => "gunungsitoli", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1301", "m_province_id" => "13", "level" => "kabupaten", "name" => "kepulauan mentawai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1302", "m_province_id" => "13", "level" => "kabupaten", "name" => "pesisir selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1303", "m_province_id" => "13", "level" => "kabupaten", "name" => "solok", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1304", "m_province_id" => "13", "level" => "kabupaten", "name" => "sijunjung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1305", "m_province_id" => "13", "level" => "kabupaten", "name" => "tanah datar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1306", "m_province_id" => "13", "level" => "kabupaten", "name" => "padang pariaman", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1307", "m_province_id" => "13", "level" => "kabupaten", "name" => "agam", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1308", "m_province_id" => "13", "level" => "kabupaten", "name" => "lima puluh kota", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1309", "m_province_id" => "13", "level" => "kabupaten", "name" => "pasaman", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1310", "m_province_id" => "13", "level" => "kabupaten", "name" => "solok selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1311", "m_province_id" => "13", "level" => "kabupaten", "name" => "dharmasraya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1312", "m_province_id" => "13", "level" => "kabupaten", "name" => "pasaman barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1371", "m_province_id" => "13", "level" => "kota", "name" => "padang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1372", "m_province_id" => "13", "level" => "kota", "name" => "solok", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1373", "m_province_id" => "13", "level" => "kota", "name" => "sawah lunto", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1374", "m_province_id" => "13", "level" => "kota", "name" => "padang panjang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1375", "m_province_id" => "13", "level" => "kota", "name" => "bukittinggi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1376", "m_province_id" => "13", "level" => "kota", "name" => "payakumbuh", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1377", "m_province_id" => "13", "level" => "kota", "name" => "pariaman", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1401", "m_province_id" => "14", "level" => "kabupaten", "name" => "kuantan singingi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1402", "m_province_id" => "14", "level" => "kabupaten", "name" => "indragiri hulu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1403", "m_province_id" => "14", "level" => "kabupaten", "name" => "indragiri hilir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1404", "m_province_id" => "14", "level" => "kabupaten", "name" => "pelalawan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1405", "m_province_id" => "14", "level" => "kabupaten", "name" => "s i a k", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1406", "m_province_id" => "14", "level" => "kabupaten", "name" => "kampar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1407", "m_province_id" => "14", "level" => "kabupaten", "name" => "rokan hulu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1408", "m_province_id" => "14", "level" => "kabupaten", "name" => "bengkalis", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1409", "m_province_id" => "14", "level" => "kabupaten", "name" => "rokan hilir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1410", "m_province_id" => "14", "level" => "kabupaten", "name" => "kepulauan meranti", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1471", "m_province_id" => "14", "level" => "kota", "name" => "pekanbaru", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1473", "m_province_id" => "14", "level" => "kota", "name" => "d u m a i", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1501", "m_province_id" => "15", "level" => "kabupaten", "name" => "kerinci", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1502", "m_province_id" => "15", "level" => "kabupaten", "name" => "merangin", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1503", "m_province_id" => "15", "level" => "kabupaten", "name" => "sarolangun", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1504", "m_province_id" => "15", "level" => "kabupaten", "name" => "batang hari", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1505", "m_province_id" => "15", "level" => "kabupaten", "name" => "muaro jambi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1506", "m_province_id" => "15", "level" => "kabupaten", "name" => "tanjung jabung timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1507", "m_province_id" => "15", "level" => "kabupaten", "name" => "tanjung jabung barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1508", "m_province_id" => "15", "level" => "kabupaten", "name" => "tebo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1509", "m_province_id" => "15", "level" => "kabupaten", "name" => "bungo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1571", "m_province_id" => "15", "level" => "kota", "name" => "jambi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1572", "m_province_id" => "15", "level" => "kota", "name" => "sungai penuh", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1601", "m_province_id" => "16", "level" => "kabupaten", "name" => "ogan komering ulu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1602", "m_province_id" => "16", "level" => "kabupaten", "name" => "ogan komering ilir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1603", "m_province_id" => "16", "level" => "kabupaten", "name" => "muara enim", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1604", "m_province_id" => "16", "level" => "kabupaten", "name" => "lahat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1605", "m_province_id" => "16", "level" => "kabupaten", "name" => "musi rawas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1606", "m_province_id" => "16", "level" => "kabupaten", "name" => "musi banyuasin", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1607", "m_province_id" => "16", "level" => "kabupaten", "name" => "banyu asin", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1608", "m_province_id" => "16", "level" => "kabupaten", "name" => "ogan komering ulu selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1609", "m_province_id" => "16", "level" => "kabupaten", "name" => "ogan komering ulu timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1610", "m_province_id" => "16", "level" => "kabupaten", "name" => "ogan ilir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1611", "m_province_id" => "16", "level" => "kabupaten", "name" => "empat lawang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1612", "m_province_id" => "16", "level" => "kabupaten", "name" => "penukal abab lematang ilir", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1613", "m_province_id" => "16", "level" => "kabupaten", "name" => "musi rawas utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1671", "m_province_id" => "16", "level" => "kota", "name" => "palembang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1672", "m_province_id" => "16", "level" => "kota", "name" => "prabumulih", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1673", "m_province_id" => "16", "level" => "kota", "name" => "pagar alam", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1674", "m_province_id" => "16", "level" => "kota", "name" => "lubuklinggau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1701", "m_province_id" => "17", "level" => "kabupaten", "name" => "bengkulu selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1702", "m_province_id" => "17", "level" => "kabupaten", "name" => "rejang lebong", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1703", "m_province_id" => "17", "level" => "kabupaten", "name" => "bengkulu utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1704", "m_province_id" => "17", "level" => "kabupaten", "name" => "kaur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1705", "m_province_id" => "17", "level" => "kabupaten", "name" => "seluma", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1706", "m_province_id" => "17", "level" => "kabupaten", "name" => "mukomuko", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1707", "m_province_id" => "17", "level" => "kabupaten", "name" => "lebong", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1708", "m_province_id" => "17", "level" => "kabupaten", "name" => "kepahiang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1709", "m_province_id" => "17", "level" => "kabupaten", "name" => "bengkulu tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1771", "m_province_id" => "17", "level" => "kota", "name" => "bengkulu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1801", "m_province_id" => "18", "level" => "kabupaten", "name" => "lampung barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1802", "m_province_id" => "18", "level" => "kabupaten", "name" => "tanggamus", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1803", "m_province_id" => "18", "level" => "kabupaten", "name" => "lampung selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1804", "m_province_id" => "18", "level" => "kabupaten", "name" => "lampung timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1805", "m_province_id" => "18", "level" => "kabupaten", "name" => "lampung tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1806", "m_province_id" => "18", "level" => "kabupaten", "name" => "lampung utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1807", "m_province_id" => "18", "level" => "kabupaten", "name" => "way kanan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1808", "m_province_id" => "18", "level" => "kabupaten", "name" => "tulangbawang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1809", "m_province_id" => "18", "level" => "kabupaten", "name" => "pesawaran", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1810", "m_province_id" => "18", "level" => "kabupaten", "name" => "pringsewu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1811", "m_province_id" => "18", "level" => "kabupaten", "name" => "mesuji", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1812", "m_province_id" => "18", "level" => "kabupaten", "name" => "tulang bawang barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1813", "m_province_id" => "18", "level" => "kabupaten", "name" => "pesisir barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1871", "m_province_id" => "18", "level" => "kota", "name" => "bandar lampung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1872", "m_province_id" => "18", "level" => "kota", "name" => "metro", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1901", "m_province_id" => "19", "level" => "kabupaten", "name" => "bangka", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1902", "m_province_id" => "19", "level" => "kabupaten", "name" => "belitung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1903", "m_province_id" => "19", "level" => "kabupaten", "name" => "bangka barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1904", "m_province_id" => "19", "level" => "kabupaten", "name" => "bangka tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1905", "m_province_id" => "19", "level" => "kabupaten", "name" => "bangka selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1906", "m_province_id" => "19", "level" => "kabupaten", "name" => "belitung timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "1971", "m_province_id" => "19", "level" => "kota", "name" => "pangkal pinang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2101", "m_province_id" => "21", "level" => "kabupaten", "name" => "karimun", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2102", "m_province_id" => "21", "level" => "kabupaten", "name" => "bintan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2103", "m_province_id" => "21", "level" => "kabupaten", "name" => "natuna", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2104", "m_province_id" => "21", "level" => "kabupaten", "name" => "lingga", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2105", "m_province_id" => "21", "level" => "kabupaten", "name" => "kepulauan anambas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2171", "m_province_id" => "21", "level" => "kota", "name" => "b a t a m", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "2172", "m_province_id" => "21", "level" => "kota", "name" => "tanjung pinang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3101", "m_province_id" => "31", "level" => "kabupaten", "name" => "kepulauan seribu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3171", "m_province_id" => "31", "level" => "kota", "name" => "jakarta selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3172", "m_province_id" => "31", "level" => "kota", "name" => "jakarta timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3173", "m_province_id" => "31", "level" => "kota", "name" => "jakarta pusat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3174", "m_province_id" => "31", "level" => "kota", "name" => "jakarta barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3175", "m_province_id" => "31", "level" => "kota", "name" => "jakarta utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3201", "m_province_id" => "32", "level" => "kabupaten", "name" => "bogor", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3202", "m_province_id" => "32", "level" => "kabupaten", "name" => "sukabumi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3203", "m_province_id" => "32", "level" => "kabupaten", "name" => "cianjur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3204", "m_province_id" => "32", "level" => "kabupaten", "name" => "bandung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3205", "m_province_id" => "32", "level" => "kabupaten", "name" => "garut", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3206", "m_province_id" => "32", "level" => "kabupaten", "name" => "tasikmalaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3207", "m_province_id" => "32", "level" => "kabupaten", "name" => "ciamis", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3208", "m_province_id" => "32", "level" => "kabupaten", "name" => "kuningan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3209", "m_province_id" => "32", "level" => "kabupaten", "name" => "cirebon", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3210", "m_province_id" => "32", "level" => "kabupaten", "name" => "majalengka", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3211", "m_province_id" => "32", "level" => "kabupaten", "name" => "sumedang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3212", "m_province_id" => "32", "level" => "kabupaten", "name" => "indramayu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3213", "m_province_id" => "32", "level" => "kabupaten", "name" => "subang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3214", "m_province_id" => "32", "level" => "kabupaten", "name" => "purwakarta", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3215", "m_province_id" => "32", "level" => "kabupaten", "name" => "karawang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3216", "m_province_id" => "32", "level" => "kabupaten", "name" => "bekasi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3217", "m_province_id" => "32", "level" => "kabupaten", "name" => "bandung barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3218", "m_province_id" => "32", "level" => "kabupaten", "name" => "pangandaran", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3271", "m_province_id" => "32", "level" => "kota", "name" => "bogor", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3272", "m_province_id" => "32", "level" => "kota", "name" => "sukabumi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3273", "m_province_id" => "32", "level" => "kota", "name" => "bandung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3274", "m_province_id" => "32", "level" => "kota", "name" => "cirebon", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3275", "m_province_id" => "32", "level" => "kota", "name" => "bekasi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3276", "m_province_id" => "32", "level" => "kota", "name" => "depok", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3277", "m_province_id" => "32", "level" => "kota", "name" => "cimahi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3278", "m_province_id" => "32", "level" => "kota", "name" => "tasikmalaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3279", "m_province_id" => "32", "level" => "kota", "name" => "banjar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3301", "m_province_id" => "33", "level" => "kabupaten", "name" => "cilacap", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3302", "m_province_id" => "33", "level" => "kabupaten", "name" => "banyumas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3303", "m_province_id" => "33", "level" => "kabupaten", "name" => "purbalingga", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3304", "m_province_id" => "33", "level" => "kabupaten", "name" => "banjarnegara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3305", "m_province_id" => "33", "level" => "kabupaten", "name" => "kebumen", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3306", "m_province_id" => "33", "level" => "kabupaten", "name" => "purworejo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3307", "m_province_id" => "33", "level" => "kabupaten", "name" => "wonosobo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3308", "m_province_id" => "33", "level" => "kabupaten", "name" => "magelang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3309", "m_province_id" => "33", "level" => "kabupaten", "name" => "boyolali", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3310", "m_province_id" => "33", "level" => "kabupaten", "name" => "klaten", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3311", "m_province_id" => "33", "level" => "kabupaten", "name" => "sukoharjo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3312", "m_province_id" => "33", "level" => "kabupaten", "name" => "wonogiri", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3313", "m_province_id" => "33", "level" => "kabupaten", "name" => "karanganyar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3314", "m_province_id" => "33", "level" => "kabupaten", "name" => "sragen", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3315", "m_province_id" => "33", "level" => "kabupaten", "name" => "grobogan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3316", "m_province_id" => "33", "level" => "kabupaten", "name" => "blora", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3317", "m_province_id" => "33", "level" => "kabupaten", "name" => "rembang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3318", "m_province_id" => "33", "level" => "kabupaten", "name" => "pati", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3319", "m_province_id" => "33", "level" => "kabupaten", "name" => "kudus", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3320", "m_province_id" => "33", "level" => "kabupaten", "name" => "jepara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3321", "m_province_id" => "33", "level" => "kabupaten", "name" => "demak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3322", "m_province_id" => "33", "level" => "kabupaten", "name" => "semarang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3323", "m_province_id" => "33", "level" => "kabupaten", "name" => "temanggung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3324", "m_province_id" => "33", "level" => "kabupaten", "name" => "kendal", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3325", "m_province_id" => "33", "level" => "kabupaten", "name" => "batang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3326", "m_province_id" => "33", "level" => "kabupaten", "name" => "pekalongan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3327", "m_province_id" => "33", "level" => "kabupaten", "name" => "pemalang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3328", "m_province_id" => "33", "level" => "kabupaten", "name" => "tegal", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3329", "m_province_id" => "33", "level" => "kabupaten", "name" => "brebes", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3371", "m_province_id" => "33", "level" => "kota", "name" => "magelang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3372", "m_province_id" => "33", "level" => "kota", "name" => "surakarta", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3373", "m_province_id" => "33", "level" => "kota", "name" => "salatiga", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3374", "m_province_id" => "33", "level" => "kota", "name" => "semarang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3375", "m_province_id" => "33", "level" => "kota", "name" => "pekalongan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3376", "m_province_id" => "33", "level" => "kota", "name" => "tegal", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3401", "m_province_id" => "34", "level" => "kabupaten", "name" => "kulon progo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3402", "m_province_id" => "34", "level" => "kabupaten", "name" => "bantul", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3403", "m_province_id" => "34", "level" => "kabupaten", "name" => "gunung kidul", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3404", "m_province_id" => "34", "level" => "kabupaten", "name" => "sleman", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3471", "m_province_id" => "34", "level" => "kota", "name" => "yogyakarta", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3501", "m_province_id" => "35", "level" => "kabupaten", "name" => "pacitan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3502", "m_province_id" => "35", "level" => "kabupaten", "name" => "ponorogo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3503", "m_province_id" => "35", "level" => "kabupaten", "name" => "trenggalek", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3504", "m_province_id" => "35", "level" => "kabupaten", "name" => "tulungagung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3505", "m_province_id" => "35", "level" => "kabupaten", "name" => "blitar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3506", "m_province_id" => "35", "level" => "kabupaten", "name" => "kediri", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3507", "m_province_id" => "35", "level" => "kabupaten", "name" => "malang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3508", "m_province_id" => "35", "level" => "kabupaten", "name" => "lumajang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3509", "m_province_id" => "35", "level" => "kabupaten", "name" => "jember", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3510", "m_province_id" => "35", "level" => "kabupaten", "name" => "banyuwangi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3511", "m_province_id" => "35", "level" => "kabupaten", "name" => "bondowoso", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3512", "m_province_id" => "35", "level" => "kabupaten", "name" => "situbondo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3513", "m_province_id" => "35", "level" => "kabupaten", "name" => "probolinggo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3514", "m_province_id" => "35", "level" => "kabupaten", "name" => "pasuruan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3515", "m_province_id" => "35", "level" => "kabupaten", "name" => "sidoarjo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3516", "m_province_id" => "35", "level" => "kabupaten", "name" => "mojokerto", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3517", "m_province_id" => "35", "level" => "kabupaten", "name" => "jombang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3518", "m_province_id" => "35", "level" => "kabupaten", "name" => "nganjuk", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3519", "m_province_id" => "35", "level" => "kabupaten", "name" => "madiun", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3520", "m_province_id" => "35", "level" => "kabupaten", "name" => "magetan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3521", "m_province_id" => "35", "level" => "kabupaten", "name" => "ngawi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3522", "m_province_id" => "35", "level" => "kabupaten", "name" => "bojonegoro", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3523", "m_province_id" => "35", "level" => "kabupaten", "name" => "tuban", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3524", "m_province_id" => "35", "level" => "kabupaten", "name" => "lamongan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3525", "m_province_id" => "35", "level" => "kabupaten", "name" => "gresik", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3526", "m_province_id" => "35", "level" => "kabupaten", "name" => "bangkalan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3527", "m_province_id" => "35", "level" => "kabupaten", "name" => "sampang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3528", "m_province_id" => "35", "level" => "kabupaten", "name" => "pamekasan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3529", "m_province_id" => "35", "level" => "kabupaten", "name" => "sumenep", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3571", "m_province_id" => "35", "level" => "kota", "name" => "kediri", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3572", "m_province_id" => "35", "level" => "kota", "name" => "blitar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3573", "m_province_id" => "35", "level" => "kota", "name" => "malang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3574", "m_province_id" => "35", "level" => "kota", "name" => "probolinggo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3575", "m_province_id" => "35", "level" => "kota", "name" => "pasuruan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3576", "m_province_id" => "35", "level" => "kota", "name" => "mojokerto", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3577", "m_province_id" => "35", "level" => "kota", "name" => "madiun", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3578", "m_province_id" => "35", "level" => "kota", "name" => "surabaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3579", "m_province_id" => "35", "level" => "kota", "name" => "batu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3601", "m_province_id" => "36", "level" => "kabupaten", "name" => "pandeglang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3602", "m_province_id" => "36", "level" => "kabupaten", "name" => "lebak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3603", "m_province_id" => "36", "level" => "kabupaten", "name" => "tangerang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3604", "m_province_id" => "36", "level" => "kabupaten", "name" => "serang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3671", "m_province_id" => "36", "level" => "kota", "name" => "tangerang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3672", "m_province_id" => "36", "level" => "kota", "name" => "cilegon", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3673", "m_province_id" => "36", "level" => "kota", "name" => "serang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "3674", "m_province_id" => "36", "level" => "kota", "name" => "tangerang selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5101", "m_province_id" => "51", "level" => "kabupaten", "name" => "jembrana", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5102", "m_province_id" => "51", "level" => "kabupaten", "name" => "tabanan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5103", "m_province_id" => "51", "level" => "kabupaten", "name" => "badung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5104", "m_province_id" => "51", "level" => "kabupaten", "name" => "gianyar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5105", "m_province_id" => "51", "level" => "kabupaten", "name" => "klungkung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5106", "m_province_id" => "51", "level" => "kabupaten", "name" => "bangli", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5107", "m_province_id" => "51", "level" => "kabupaten", "name" => "karang asem", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5108", "m_province_id" => "51", "level" => "kabupaten", "name" => "buleleng", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5171", "m_province_id" => "51", "level" => "kota", "name" => "denpasar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5201", "m_province_id" => "52", "level" => "kabupaten", "name" => "lombok barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5202", "m_province_id" => "52", "level" => "kabupaten", "name" => "lombok tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5203", "m_province_id" => "52", "level" => "kabupaten", "name" => "lombok timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5204", "m_province_id" => "52", "level" => "kabupaten", "name" => "sumbawa", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5205", "m_province_id" => "52", "level" => "kabupaten", "name" => "dompu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5206", "m_province_id" => "52", "level" => "kabupaten", "name" => "bima", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5207", "m_province_id" => "52", "level" => "kabupaten", "name" => "sumbawa barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5208", "m_province_id" => "52", "level" => "kabupaten", "name" => "lombok utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5271", "m_province_id" => "52", "level" => "kota", "name" => "mataram", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5272", "m_province_id" => "52", "level" => "kota", "name" => "bima", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5301", "m_province_id" => "53", "level" => "kabupaten", "name" => "sumba barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5302", "m_province_id" => "53", "level" => "kabupaten", "name" => "sumba timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5303", "m_province_id" => "53", "level" => "kabupaten", "name" => "kupang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5304", "m_province_id" => "53", "level" => "kabupaten", "name" => "timor tengah selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5305", "m_province_id" => "53", "level" => "kabupaten", "name" => "timor tengah utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5306", "m_province_id" => "53", "level" => "kabupaten", "name" => "belu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5307", "m_province_id" => "53", "level" => "kabupaten", "name" => "alor", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5308", "m_province_id" => "53", "level" => "kabupaten", "name" => "lembata", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5309", "m_province_id" => "53", "level" => "kabupaten", "name" => "flores timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5310", "m_province_id" => "53", "level" => "kabupaten", "name" => "sikka", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5311", "m_province_id" => "53", "level" => "kabupaten", "name" => "ende", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5312", "m_province_id" => "53", "level" => "kabupaten", "name" => "ngada", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5313", "m_province_id" => "53", "level" => "kabupaten", "name" => "manggarai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5314", "m_province_id" => "53", "level" => "kabupaten", "name" => "rote ndao", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5315", "m_province_id" => "53", "level" => "kabupaten", "name" => "manggarai barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5316", "m_province_id" => "53", "level" => "kabupaten", "name" => "sumba tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5317", "m_province_id" => "53", "level" => "kabupaten", "name" => "sumba barat daya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5318", "m_province_id" => "53", "level" => "kabupaten", "name" => "nagekeo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5319", "m_province_id" => "53", "level" => "kabupaten", "name" => "manggarai timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5320", "m_province_id" => "53", "level" => "kabupaten", "name" => "sabu raijua", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5321", "m_province_id" => "53", "level" => "kabupaten", "name" => "malaka", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "5371", "m_province_id" => "53", "level" => "kota", "name" => "kupang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6101", "m_province_id" => "61", "level" => "kabupaten", "name" => "sambas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6102", "m_province_id" => "61", "level" => "kabupaten", "name" => "bengkayang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6103", "m_province_id" => "61", "level" => "kabupaten", "name" => "landak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6104", "m_province_id" => "61", "level" => "kabupaten", "name" => "mempawah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6105", "m_province_id" => "61", "level" => "kabupaten", "name" => "sanggau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6106", "m_province_id" => "61", "level" => "kabupaten", "name" => "ketapang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6107", "m_province_id" => "61", "level" => "kabupaten", "name" => "sintang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6108", "m_province_id" => "61", "level" => "kabupaten", "name" => "kapuas hulu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6109", "m_province_id" => "61", "level" => "kabupaten", "name" => "sekadau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6110", "m_province_id" => "61", "level" => "kabupaten", "name" => "melawi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6111", "m_province_id" => "61", "level" => "kabupaten", "name" => "kayong utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6112", "m_province_id" => "61", "level" => "kabupaten", "name" => "kubu raya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6171", "m_province_id" => "61", "level" => "kota", "name" => "pontianak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6172", "m_province_id" => "61", "level" => "kota", "name" => "singkawang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6201", "m_province_id" => "62", "level" => "kabupaten", "name" => "kotawaringin barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6202", "m_province_id" => "62", "level" => "kabupaten", "name" => "kotawaringin timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6203", "m_province_id" => "62", "level" => "kabupaten", "name" => "kapuas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6204", "m_province_id" => "62", "level" => "kabupaten", "name" => "barito selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6205", "m_province_id" => "62", "level" => "kabupaten", "name" => "barito utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6206", "m_province_id" => "62", "level" => "kabupaten", "name" => "sukamara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6207", "m_province_id" => "62", "level" => "kabupaten", "name" => "lamandau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6208", "m_province_id" => "62", "level" => "kabupaten", "name" => "seruyan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6209", "m_province_id" => "62", "level" => "kabupaten", "name" => "katingan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6210", "m_province_id" => "62", "level" => "kabupaten", "name" => "pulang pisau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6211", "m_province_id" => "62", "level" => "kabupaten", "name" => "gunung mas", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6212", "m_province_id" => "62", "level" => "kabupaten", "name" => "barito timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6213", "m_province_id" => "62", "level" => "kabupaten", "name" => "murung raya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6271", "m_province_id" => "62", "level" => "kota", "name" => "palangka raya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6301", "m_province_id" => "63", "level" => "kabupaten", "name" => "tanah laut", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6302", "m_province_id" => "63", "level" => "kabupaten", "name" => "kota baru", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6303", "m_province_id" => "63", "level" => "kabupaten", "name" => "banjar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6304", "m_province_id" => "63", "level" => "kabupaten", "name" => "barito kuala", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6305", "m_province_id" => "63", "level" => "kabupaten", "name" => "tapin", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6306", "m_province_id" => "63", "level" => "kabupaten", "name" => "hulu sungai selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6307", "m_province_id" => "63", "level" => "kabupaten", "name" => "hulu sungai tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6308", "m_province_id" => "63", "level" => "kabupaten", "name" => "hulu sungai utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6309", "m_province_id" => "63", "level" => "kabupaten", "name" => "tabalong", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6310", "m_province_id" => "63", "level" => "kabupaten", "name" => "tanah bumbu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6311", "m_province_id" => "63", "level" => "kabupaten", "name" => "balangan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6371", "m_province_id" => "63", "level" => "kota", "name" => "banjarmasin", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6372", "m_province_id" => "63", "level" => "kota", "name" => "banjar baru", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6401", "m_province_id" => "64", "level" => "kabupaten", "name" => "paser", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6402", "m_province_id" => "64", "level" => "kabupaten", "name" => "kutai barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6403", "m_province_id" => "64", "level" => "kabupaten", "name" => "kutai kartanegara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6404", "m_province_id" => "64", "level" => "kabupaten", "name" => "kutai timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6405", "m_province_id" => "64", "level" => "kabupaten", "name" => "berau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6409", "m_province_id" => "64", "level" => "kabupaten", "name" => "penajam paser utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6411", "m_province_id" => "64", "level" => "kabupaten", "name" => "mahakam hulu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6471", "m_province_id" => "64", "level" => "kota", "name" => "balikpapan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6472", "m_province_id" => "64", "level" => "kota", "name" => "samarinda", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6474", "m_province_id" => "64", "level" => "kota", "name" => "bontang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6501", "m_province_id" => "65", "level" => "kabupaten", "name" => "malinau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6502", "m_province_id" => "65", "level" => "kabupaten", "name" => "bulungan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6503", "m_province_id" => "65", "level" => "kabupaten", "name" => "tana tidung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6504", "m_province_id" => "65", "level" => "kabupaten", "name" => "nunukan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "6571", "m_province_id" => "65", "level" => "kota", "name" => "tarakan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7101", "m_province_id" => "71", "level" => "kabupaten", "name" => "bolaang mongondow", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7102", "m_province_id" => "71", "level" => "kabupaten", "name" => "minahasa", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7103", "m_province_id" => "71", "level" => "kabupaten", "name" => "kepulauan sangihe", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7104", "m_province_id" => "71", "level" => "kabupaten", "name" => "kepulauan talaud", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7105", "m_province_id" => "71", "level" => "kabupaten", "name" => "minahasa selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7106", "m_province_id" => "71", "level" => "kabupaten", "name" => "minahasa utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7107", "m_province_id" => "71", "level" => "kabupaten", "name" => "bolaang mongondow utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7108", "m_province_id" => "71", "level" => "kabupaten", "name" => "siau tagulandang biaro", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7109", "m_province_id" => "71", "level" => "kabupaten", "name" => "minahasa tenggara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7110", "m_province_id" => "71", "level" => "kabupaten", "name" => "bolaang mongondow selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7111", "m_province_id" => "71", "level" => "kabupaten", "name" => "bolaang mongondow timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7171", "m_province_id" => "71", "level" => "kota", "name" => "manado", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7172", "m_province_id" => "71", "level" => "kota", "name" => "bitung", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7173", "m_province_id" => "71", "level" => "kota", "name" => "tomohon", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7174", "m_province_id" => "71", "level" => "kota", "name" => "kotamobagu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7201", "m_province_id" => "72", "level" => "kabupaten", "name" => "banggai kepulauan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7202", "m_province_id" => "72", "level" => "kabupaten", "name" => "banggai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7203", "m_province_id" => "72", "level" => "kabupaten", "name" => "morowali", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7204", "m_province_id" => "72", "level" => "kabupaten", "name" => "poso", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7205", "m_province_id" => "72", "level" => "kabupaten", "name" => "donggala", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7206", "m_province_id" => "72", "level" => "kabupaten", "name" => "toli-toli", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7207", "m_province_id" => "72", "level" => "kabupaten", "name" => "buol", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7208", "m_province_id" => "72", "level" => "kabupaten", "name" => "parigi moutong", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7209", "m_province_id" => "72", "level" => "kabupaten", "name" => "tojo una-una", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7210", "m_province_id" => "72", "level" => "kabupaten", "name" => "sigi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7211", "m_province_id" => "72", "level" => "kabupaten", "name" => "banggai laut", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7212", "m_province_id" => "72", "level" => "kabupaten", "name" => "morowali utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7271", "m_province_id" => "72", "level" => "kota", "name" => "palu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7301", "m_province_id" => "73", "level" => "kabupaten", "name" => "kepulauan selayar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7302", "m_province_id" => "73", "level" => "kabupaten", "name" => "bulukumba", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7303", "m_province_id" => "73", "level" => "kabupaten", "name" => "bantaeng", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7304", "m_province_id" => "73", "level" => "kabupaten", "name" => "jeneponto", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7305", "m_province_id" => "73", "level" => "kabupaten", "name" => "takalar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7306", "m_province_id" => "73", "level" => "kabupaten", "name" => "gowa", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7307", "m_province_id" => "73", "level" => "kabupaten", "name" => "sinjai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7308", "m_province_id" => "73", "level" => "kabupaten", "name" => "maros", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7309", "m_province_id" => "73", "level" => "kabupaten", "name" => "pangkajene dan kepulauan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7310", "m_province_id" => "73", "level" => "kabupaten", "name" => "barru", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7311", "m_province_id" => "73", "level" => "kabupaten", "name" => "bone", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7312", "m_province_id" => "73", "level" => "kabupaten", "name" => "soppeng", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7313", "m_province_id" => "73", "level" => "kabupaten", "name" => "wajo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7314", "m_province_id" => "73", "level" => "kabupaten", "name" => "sidenreng rappang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7315", "m_province_id" => "73", "level" => "kabupaten", "name" => "pinrang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7316", "m_province_id" => "73", "level" => "kabupaten", "name" => "enrekang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7317", "m_province_id" => "73", "level" => "kabupaten", "name" => "luwu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7318", "m_province_id" => "73", "level" => "kabupaten", "name" => "tana toraja", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7322", "m_province_id" => "73", "level" => "kabupaten", "name" => "luwu utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7325", "m_province_id" => "73", "level" => "kabupaten", "name" => "luwu timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7326", "m_province_id" => "73", "level" => "kabupaten", "name" => "toraja utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7371", "m_province_id" => "73", "level" => "kota", "name" => "makassar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7372", "m_province_id" => "73", "level" => "kota", "name" => "parepare", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7373", "m_province_id" => "73", "level" => "kota", "name" => "palopo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7401", "m_province_id" => "74", "level" => "kabupaten", "name" => "buton", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7402", "m_province_id" => "74", "level" => "kabupaten", "name" => "muna", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7403", "m_province_id" => "74", "level" => "kabupaten", "name" => "konawe", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7404", "m_province_id" => "74", "level" => "kabupaten", "name" => "kolaka", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7405", "m_province_id" => "74", "level" => "kabupaten", "name" => "konawe selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7406", "m_province_id" => "74", "level" => "kabupaten", "name" => "bombana", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7407", "m_province_id" => "74", "level" => "kabupaten", "name" => "wakatobi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7408", "m_province_id" => "74", "level" => "kabupaten", "name" => "kolaka utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7409", "m_province_id" => "74", "level" => "kabupaten", "name" => "buton utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7410", "m_province_id" => "74", "level" => "kabupaten", "name" => "konawe utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7411", "m_province_id" => "74", "level" => "kabupaten", "name" => "kolaka timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7412", "m_province_id" => "74", "level" => "kabupaten", "name" => "konawe kepulauan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7413", "m_province_id" => "74", "level" => "kabupaten", "name" => "muna barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7414", "m_province_id" => "74", "level" => "kabupaten", "name" => "buton tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7415", "m_province_id" => "74", "level" => "kabupaten", "name" => "buton selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7471", "m_province_id" => "74", "level" => "kota", "name" => "kendari", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7472", "m_province_id" => "74", "level" => "kota", "name" => "baubau", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7501", "m_province_id" => "75", "level" => "kabupaten", "name" => "boalemo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7502", "m_province_id" => "75", "level" => "kabupaten", "name" => "gorontalo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7503", "m_province_id" => "75", "level" => "kabupaten", "name" => "pohuwato", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7504", "m_province_id" => "75", "level" => "kabupaten", "name" => "bone bolango", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7505", "m_province_id" => "75", "level" => "kabupaten", "name" => "gorontalo utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7571", "m_province_id" => "75", "level" => "kota", "name" => "gorontalo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7601", "m_province_id" => "76", "level" => "kabupaten", "name" => "majene", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7602", "m_province_id" => "76", "level" => "kabupaten", "name" => "polewali mandar", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7603", "m_province_id" => "76", "level" => "kabupaten", "name" => "mamasa", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7604", "m_province_id" => "76", "level" => "kabupaten", "name" => "mamuju", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7605", "m_province_id" => "76", "level" => "kabupaten", "name" => "mamuju utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "7606", "m_province_id" => "76", "level" => "kabupaten", "name" => "mamuju tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8101", "m_province_id" => "81", "level" => "kabupaten", "name" => "maluku tenggara barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8102", "m_province_id" => "81", "level" => "kabupaten", "name" => "maluku tenggara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8103", "m_province_id" => "81", "level" => "kabupaten", "name" => "maluku tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8104", "m_province_id" => "81", "level" => "kabupaten", "name" => "buru", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8105", "m_province_id" => "81", "level" => "kabupaten", "name" => "kepulauan aru", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8106", "m_province_id" => "81", "level" => "kabupaten", "name" => "seram bagian barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8107", "m_province_id" => "81", "level" => "kabupaten", "name" => "seram bagian timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8108", "m_province_id" => "81", "level" => "kabupaten", "name" => "maluku barat daya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8109", "m_province_id" => "81", "level" => "kabupaten", "name" => "buru selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8171", "m_province_id" => "81", "level" => "kota", "name" => "ambon", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8172", "m_province_id" => "81", "level" => "kota", "name" => "tual", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8201", "m_province_id" => "82", "level" => "kabupaten", "name" => "halmahera barat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8202", "m_province_id" => "82", "level" => "kabupaten", "name" => "halmahera tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8203", "m_province_id" => "82", "level" => "kabupaten", "name" => "kepulauan sula", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8204", "m_province_id" => "82", "level" => "kabupaten", "name" => "halmahera selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8205", "m_province_id" => "82", "level" => "kabupaten", "name" => "halmahera utara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8206", "m_province_id" => "82", "level" => "kabupaten", "name" => "halmahera timur", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8207", "m_province_id" => "82", "level" => "kabupaten", "name" => "pulau morotai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8208", "m_province_id" => "82", "level" => "kabupaten", "name" => "pulau taliabu", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8271", "m_province_id" => "82", "level" => "kota", "name" => "ternate", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "8272", "m_province_id" => "82", "level" => "kota", "name" => "tidore kepulauan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9101", "m_province_id" => "91", "level" => "kabupaten", "name" => "fakfak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9102", "m_province_id" => "91", "level" => "kabupaten", "name" => "kaimana", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9103", "m_province_id" => "91", "level" => "kabupaten", "name" => "teluk wondama", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9104", "m_province_id" => "91", "level" => "kabupaten", "name" => "teluk bintuni", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9105", "m_province_id" => "91", "level" => "kabupaten", "name" => "manokwari", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9106", "m_province_id" => "91", "level" => "kabupaten", "name" => "sorong selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9107", "m_province_id" => "91", "level" => "kabupaten", "name" => "sorong", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9108", "m_province_id" => "91", "level" => "kabupaten", "name" => "raja ampat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9109", "m_province_id" => "91", "level" => "kabupaten", "name" => "tambrauw", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9110", "m_province_id" => "91", "level" => "kabupaten", "name" => "maybrat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9111", "m_province_id" => "91", "level" => "kabupaten", "name" => "manokwari selatan", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9112", "m_province_id" => "91", "level" => "kabupaten", "name" => "pegunungan arfak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9171", "m_province_id" => "91", "level" => "kota", "name" => "sorong", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9401", "m_province_id" => "94", "level" => "kabupaten", "name" => "merauke", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9402", "m_province_id" => "94", "level" => "kabupaten", "name" => "jayawijaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9403", "m_province_id" => "94", "level" => "kabupaten", "name" => "jayapura", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9404", "m_province_id" => "94", "level" => "kabupaten", "name" => "nabire", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9408", "m_province_id" => "94", "level" => "kabupaten", "name" => "kepulauan yapen", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9409", "m_province_id" => "94", "level" => "kabupaten", "name" => "biak numfor", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9410", "m_province_id" => "94", "level" => "kabupaten", "name" => "paniai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9411", "m_province_id" => "94", "level" => "kabupaten", "name" => "puncak jaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9412", "m_province_id" => "94", "level" => "kabupaten", "name" => "mimika", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9413", "m_province_id" => "94", "level" => "kabupaten", "name" => "boven digoel", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9414", "m_province_id" => "94", "level" => "kabupaten", "name" => "mappi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9415", "m_province_id" => "94", "level" => "kabupaten", "name" => "asmat", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9416", "m_province_id" => "94", "level" => "kabupaten", "name" => "yahukimo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9417", "m_province_id" => "94", "level" => "kabupaten", "name" => "pegunungan bintang", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9418", "m_province_id" => "94", "level" => "kabupaten", "name" => "tolikara", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9419", "m_province_id" => "94", "level" => "kabupaten", "name" => "sarmi", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9420", "m_province_id" => "94", "level" => "kabupaten", "name" => "keerom", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9426", "m_province_id" => "94", "level" => "kabupaten", "name" => "waropen", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9427", "m_province_id" => "94", "level" => "kabupaten", "name" => "supiori", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9428", "m_province_id" => "94", "level" => "kabupaten", "name" => "mamberamo raya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9429", "m_province_id" => "94", "level" => "kabupaten", "name" => "nduga", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9430", "m_province_id" => "94", "level" => "kabupaten", "name" => "lanny jaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9431", "m_province_id" => "94", "level" => "kabupaten", "name" => "mamberamo tengah", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9432", "m_province_id" => "94", "level" => "kabupaten", "name" => "yalimo", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9433", "m_province_id" => "94", "level" => "kabupaten", "name" => "puncak", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9434", "m_province_id" => "94", "level" => "kabupaten", "name" => "dogiyai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9435", "m_province_id" => "94", "level" => "kabupaten", "name" => "intan jaya", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9436", "m_province_id" => "94", "level" => "kabupaten", "name" => "deiyai", "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["id" => "9471", "m_province_id" => "94", "level" => "kota", "name" => "jayapura", "created_at" => Carbon::now(), "updated_at" => Carbon::now()]
        );

        foreach ($cities as $city) {
            DB::table('m_cities')->insert($city);
        }
    }
}
