<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Worker;
use Faker\Generator as Faker;
use Illuminate\Support\Facades\Hash;

$factory->define(Worker::class, function (Faker $faker) {
    return [
        'type' => $faker->randomElement(['internal', 'external']),
        'full_name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'phone' => '62'.$faker->unique()->numberBetween(00000000000, 99999999999),
        'username' => $faker->userName,
        'password' => Hash::make('password'),
        'status' => 1,
        'user' => 'Auto Generated By System'
    ];
});
